# Work in progress
# ref.: https://www.digitalocean.com/community/tutorials/how-to-containerize-a-laravel-application-for-development-with-docker-compose-on-ubuntu-18-04-pt
# ref.: https://www.howtoforge.com/dockerizing-laravel-with-nginx-mysql-and-docker-compose/
# ref.: https://hub.docker.com/r/bitnami/laravel

version: '2'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ~/.notesapp/db:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=my_password
      - MYSQL_DATABASE=my_database
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=my_password

  app:
    tty: true
    image: ambientum/php:7.3-nginx
    environment:
      - DB_HOST=mysql
      - DB_USERNAME=my_user
      - DB_DATABASE=my_database
      - DB_PASSWORD=my_password
    depends_on:
      - mysql
    ports:
      - 8080:8080
    volumes:
      - ./:/var/www/app
